name: ids-be
services:
  app:
    build: .
    volumes:
      - ./app:/code/app # Mount the current directory to the container
      - ./trained_models:/code/trained_models
    ports:
      - 8008:8008 